[build]
  functions = "lambda-build"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/e/*"
  to = "/.netlify/functions/express"
  status = 200

[[redirects]]
  from = "/d/*"
  to = "/.netlify/functions/default"
  status = 200
